### ISSUE TITLE
Using lighting animations on tokens result in error every time scene is loaded for players.

### ISSUE THREAD

**Issue by Kelmey** [BlitzKraig/fvtt-CommunityLighting#28]
Foundry 0.7.9
CL version 0.3.1

If I make a token emit light and assign a light animation from this mod an error popup occurs every time a player loads the scene. The error doesn't happen if a GM loads the scene. 

I was using the alternate torch, blurred torch, and star light animations. The tokens with the light sources were NPCs, not player tokens. I verified the error doesn't happen if I use no animation, or a default animation.

Here is the error from the console.

foundry.js:3780 Error: User Test Player lacks permission to update Tokens in parent gEd5ruT1uhzaE6oE
    at Function._onUpdate (D:\Programs\Foundry\FoundryVTT\resources\app\dist\database\odm\embedded.js:1:7985)
    at runNextTicks (internal/process/task_queues.js:59:5)
    at processImmediate (internal/timers.js:412:9)
    at process.topLevelDomainCallback (domain.js:130:23)
    at async Socket.handleEvent (D:\Programs\Foundry\FoundryVTT\resources\app\dist\sockets.js:1:2262)
_handleError @ foundry.js:3780
foundry.js:11476 Uncaught (in promise) Error: User Test Player lacks permission to update Tokens in parent gEd5ruT1uhzaE6oE
    at Function._onUpdate (D:\Programs\Foundry\FoundryVTT\resources\app\dist\database\odm\embedded.js:1:7985)
    at runNextTicks (internal/process/task_queues.js:59:5)
    at processImmediate (internal/timers.js:412:9)
    at process.topLevelDomainCallback (domain.js:130:23)
    at async Socket.handleEvent (D:\Programs\Foundry\FoundryVTT\resources\app\dist\sockets.js:1:2262)

**Comment by Kelmey** [comment]
Same as issue 27. closing this one.
